import Link from "next/link";
import KnowledgeArticle from "@/components/workspoor/KnowledgeArticle";
import { KNOWLEDGE_ARTICLES } from "@/lib/knowledge";
import { createPageMetadata } from "@/lib/seo";
const article = KNOWLEDGE_ARTICLES[0];
export const metadata = createPageMetadata({ title: article.title, description: article.description, path: `/kennis/${article.slug}` });

export default function ProcessGuide() {
  return <KnowledgeArticle slug={article.slug} intro="Begin met een terugkerend proces waarvan je het gewenste resultaat kunt controleren. AI kan helpen bij ongestructureerde informatie, zoals tekst. Voor vaste regels is gewone automatisering vaak voldoende. De keuze volgt uit het werkprobleem." sections={[
    { id: "verschil", title: "AI of gewone automatisering?", content: <><p>Een vaste afspraak hoeft geen AI-oplossing te worden. Denk aan een herinnering versturen als een datum verstrijkt of een formulier controleren op ontbrekende velden. Regels kunnen daar duidelijk en voorspelbaar zijn.</p><p>AI komt eerder in beeld als informatie steeds anders wordt aangeleverd: klantvragen ordenen, notities samenvatten of een eerste concept maken. De uitkomst moet dan worden gecontroleerd. Een bruikbare workflow kan beide combineren: vaste regels voor verzending en toegang, AI voor een concept en een medewerker voor de beoordeling.</p></> },
    { id: "voorbeelden", title: "Welke processen zijn een mogelijke start?", content: <><p>Onderstaande situaties zijn voorbeelden om te onderzoeken, geen standaardoplossingen of beloofde resultaten.</p><ul><li><strong>Klantvragen voorbereiden.</strong> Een medewerker ontvangt een concept op basis van goedgekeurde informatie en controleert inhoud en toezeggingen voor verzending.</li><li><strong>Overleggen verwerken.</strong> Afspraken uit toegestane notities worden geordend. De deelnemers bevestigen actie, eigenaar en datum voordat de lijst wordt gebruikt.</li><li><strong>Marktinformatie samenvatten.</strong> Een team krijgt relevante wijzigingen met bronverwijzingen en beoordeelt welke gevolgen die hebben.</li><li><strong>Bestaande inhoud hergebruiken.</strong> Een goedgekeurde webtekst wordt een nieuwsbriefconcept. Een redacteur controleert feiten, toon en actualiteit.</li></ul><p>Onze <Link href="/praktijkvoorbeelden">praktijkvoorbeelden</Link> laten zien in welke specifieke werksituaties Setpiece heeft geholpen. Die resultaten zijn geen voorspelling voor een ander bedrijf.</p></> },
    { id: "selecteren", title: "Hoe kies je het eerste proces?", content: <><p>Vergelijk een klein aantal processen. Bij de <Link href="/kansenscan">Setpiece-kansenscan</Link> zijn dat er maximaal drie. Bespreek per proces:</p><ol><li><strong>Frequentie en inspanning.</strong> Hoe vaak komt het voor en hoeveel werk vraagt het, inclusief herstel en controle?</li><li><strong>Kwaliteit.</strong> Waaraan herken je een juiste uitkomst? Kun je die beoordeling herhalen?</li><li><strong>Informatie.</strong> Zijn de benodigde bronnen beschikbaar, actueel en toegestaan voor dit gebruik?</li><li><strong>Gevolgen.</strong> Wat gebeurt er bij een fout, ontbrekende bron of storing?</li><li><strong>Eigenaarschap.</strong> Wie kan het proces aanpassen en wie helpt medewerkers bij vragen?</li></ol><p>Een kleine taak met goede bronnen en een betrokken eigenaar kan een betere start zijn dan een groot proces zonder duidelijke beslisregels.</p></> },
    { id: "grenzen", title: "Wanneer begin je nog niet?", content: <><p>Stel uitvoering uit als niemand verantwoordelijk is, de gegevens niet mogen worden gebruikt of een medewerker de uitkomst niet kan beoordelen. Eerst moeten die voorwaarden helder zijn.</p><p>Laat beslissingen met personele, juridische, financiële of gezondheidsgevolgen niet volledig automatisch verlopen. Betrek de juiste inhoudelijke deskundige en onderzoek de toepasselijke voorwaarden. Ook een proces dat maar zelden voorkomt kan te weinig voordeel bieden om invoering en beheer te rechtvaardigen.</p></> },
    { id: "invoeren", title: "Hoe maak je de verbetering werkend?", content: <><p>Beschrijf de beginsituatie en test met representatieve voorbeelden, inclusief uitzonderingen. Leg vast welke gegevens worden gebruikt, wie controleert en wat er gebeurt als de uitkomst onbruikbaar is. Laat de medewerker de nieuwe werkwijze vervolgens in echt werk beproeven.</p><p>Meet verwerkingstijd én controletijd, foutcorrecties en gebruik. Pas na die test besluit je of de werkwijze kan worden uitgebreid. De <Link href="/ai-implementatie">implementatiesprint</Link> van Setpiece richt zich op maximaal twee samenhangende workflows in vier weken, met instructie en overdracht aan een proceseigenaar.</p></> },
  ]} />;
}
