import Link from "next/link";
import JsonLd from "@/components/JsonLd";
import WorkspoorShell from "@/components/workspoor/WorkspoorShell";
import ClosingCta from "@/components/workspoor/ClosingCta";
import { createPageMetadata, SITE_URL } from "@/lib/seo";
import { SERVICE_ROUTE } from "@/lib/workspoor-content";

export const metadata = createPageMetadata({ title: "AI-diensten: advies, implementatie en teamtraining", description: "Vergelijk de AI-kansenscan, implementatiesprint, groeipartnerschap en teamtraining van Setpiece. Heldere prijzen, scope en een passende volgende stap.", path: "/diensten" });

export default function ServicesPage() {
  return <WorkspoorShell activePath="/diensten">
    <JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_URL.toString() }, { "@type": "ListItem", position: 2, name: "Diensten", item: new URL("/diensten", SITE_URL).toString() }] }} />
    <section className="ws-page-hero"><div className="ws-frame"><p className="ws-context">AI-advies, uitvoering en leren</p><h1>De juiste stap voor het werk dat beter kan.</h1><p className="ws-lead">Setpiece helpt B2B-dienstverleners met 15 tot 75 medewerkers om terugkerend werk te verbeteren. Begin bij een concrete vraag: waar zit de kans, hoe maken we die werkend of wat moet het team leren?</p><p>De kansenscan, implementatiesprint en het groeipartnerschap vormen één route. Training is een eigen ingang voor teams die beter en zorgvuldiger met AI willen werken.</p></div></section>
    <section className="ws-literacy-section"><div className="ws-frame"><div className="ws-section-heading"><p>Van inzicht naar dagelijks gebruik</p><h2>Vergelijk de drie stappen.</h2></div><div className="ws-service-route">{SERVICE_ROUTE.map(service => <article key={service.href}><div><span>{service.note}</span><h3><Link href={service.href}>{service.name}</Link></h3></div><p>{service.when}</p><p>{service.result}</p><strong>{service.price}</strong><Link className="ws-text-link" href={service.href}>Bekijk scope en oplevering</Link></article>)}</div><p className="ws-route-note">Alle bedragen zijn exclusief btw. De scan wordt binnen vijf werkdagen na de werksessie opgeleverd; de sprint duurt vier weken. Het groeipartnerschap heeft een looptijd van minimaal zes maanden. Je beslist per stap over vervolg.</p></div></section>
    <section className="ws-literacy-section ws-literacy-section--mist"><div className="ws-frame ws-literacy-split"><div><p className="ws-context">Vaardigheden en werkafspraken</p><h2>AI-geletterdheid voor medewerkers.</h2></div><div><p>Een teamtraining van drie uur voor maximaal twaalf deelnemers. We oefenen met twee werksituaties, leggen afspraken vast en bespreken na ongeveer dertig dagen het gebruik. Voor een eerste kennismaking met het onderwerp is een lezing van zestig minuten beschikbaar.</p><p>Prijs op aanvraag, afgestemd op werkvorm en situatie.</p><Link className="ws-text-link" href="/ai-geletterdheid">Bekijk teamtraining en lezing</Link></div></div></section>
    <section className="ws-literacy-section"><div className="ws-frame ws-literacy-split"><div><p className="ws-context">Als standaardoplossingen tekortschieten</p><h2>Eerst onderzoeken of maatwerk past.</h2></div><div><p>Een complexere toepassing vraagt een afzonderlijke verkenning. We onderzoeken werkproces, gebruikers, gegevens, rollen en technische haalbaarheid voordat een bouwopdracht wordt begroot. De maatwerkverkenning begint vanaf € 3.500 exclusief btw.</p><Link className="ws-text-link" href="/ai-maatwerk">Bekijk de maatwerkverkenning</Link></div></div></section>
    <section className="ws-literacy-section ws-literacy-section--mist"><div className="ws-frame"><h2>Welke dienst past bij jouw vraag?</h2><ul><li><strong>De prioriteit is nog onduidelijk:</strong> start met de <Link href="/kansenscan">betaalde kansenscan</Link>.</li><li><strong>Het proces en doel zijn gekozen:</strong> bekijk de <Link href="/ai-implementatie">implementatiesprint</Link>; we toetsen eerst of de uitgangssituatie voldoende helder is.</li><li><strong>Een werkwijze draait al:</strong> bespreek <Link href="/ai-groeipartner">begeleiding en gebruikscontrole</Link>.</li><li><strong>Het team heeft vragen over AI-gebruik:</strong> kies een <Link href="/ai-geletterdheid">training of lezing</Link>.</li></ul><p>Lees ook <Link href="/werkwijze">hoe we samenwerken</Link>, <Link href="/praktijkvoorbeelden">de praktijkvoorbeelden</Link> en onze <Link href="/kennis">praktische uitleg</Link>.</p></div></section>
    <ClosingCta />
  </WorkspoorShell>;
}
