import Link from "next/link";
import KnowledgeArticle from "@/components/workspoor/KnowledgeArticle";
import { KNOWLEDGE_ARTICLES } from "@/lib/knowledge";
import { createPageMetadata } from "@/lib/seo";
const article = KNOWLEDGE_ARTICLES[1];
export const metadata = createPageMetadata({ title: article.title, description: article.description, path: `/kennis/${article.slug}` });

export default function ResultsGuide() {
  return <KnowledgeArticle slug={article.slug} intro="De kosten van AI-invoering bestaan uit meer dan software. Neem onderzoek, inrichting, oefentijd, controle en beheer mee. Meet vervolgens of het werk werkelijk sneller of beter wordt en of medewerkers de werkwijze blijven gebruiken." sections={[
    { id: "prijzen", title: "Wat kost de begeleiding van Setpiece?", content: <><p>Dit zijn de prijzen van Setpiece, geen marktgemiddelden. Alle bedragen zijn exclusief btw.</p><dl><dt><Link href="/kansenscan">AI-kansenscan: € 1.250</Link></dt><dd>Maximaal drie processen vergelijken, een prioriteit en 90-dagenroute bepalen en één kleine verbetering werkend maken, binnen vijf werkdagen na de werksessie. Bij start van een sprint binnen dertig dagen wordt € 750 verrekend.</dd><dt><Link href="/ai-implementatie">Implementatiesprint: € 7.500</Link></dt><dd>Vier weken voor maximaal twee samenhangende workflows, inclusief testen, instructie en overdracht.</dd><dt><Link href="/ai-groeipartner">Groeipartnerschap: vanaf € 2.250 per maand</Link></dt><dd>Minimaal zes maanden, voor gebruikscontrole en verbetering binnen afgesproken capaciteit. Grotere uitbreidingen worden afzonderlijk begroot.</dd><dt><Link href="/ai-geletterdheid">Teamtraining of lezing: prijs op aanvraag</Link></dt><dd>Afhankelijk van de gekozen werkvorm en situatie.</dd><dt><Link href="/ai-maatwerk">Maatwerkverkenning: vanaf € 3.500</Link></dt><dd>Onderzoek en afbakening voorafgaand aan een mogelijke bouwopdracht.</dd></dl><p>Stem vooraf af welke licenties, toegang, interne tijd en eventuele aanvullende kosten nodig zijn. De genoemde diensten geven geen recht op onbeperkte softwareontwikkeling.</p></> },
    { id: "nulmeting", title: "Wat leg je vast vóór de start?", content: <><p>Kies één werkproces en een representatieve reeks taken. Noteer volume, benodigde minuten, aantal correcties en de eisen aan een goede uitkomst. Spreek af wie meet en wanneer. Gebruik bij de eindmeting vergelijkbaar werk; een makkelijke demonstratie vergelijken met een moeilijke werkweek geeft geen bruikbaar beeld.</p><ul><li><strong>Tijd:</strong> voorbereiding, uitvoering, controle en herstel.</li><li><strong>Kwaliteit:</strong> juistheid, volledigheid en terugkerende fouten.</li><li><strong>Gebruik:</strong> hoe vaak medewerkers de nieuwe werkwijze werkelijk toepassen.</li><li><strong>Beheer:</strong> tijd en kosten voor vragen, wijzigingen en storingen.</li></ul></> },
    { id: "voorbeeld", title: "Een rekenvoorbeeld voor tijdwinst", content: <><p>Dit is een fictief voorbeeld. Een taak komt honderd keer per maand voor en kost eerst twintig minuten. Na invoering kost de uitvoering acht minuten en de controle vier minuten. De nieuwe totale tijd is twaalf minuten, dus het verschil is acht minuten per taak: achthonderd minuten, oftewel dertien uur en twintig minuten per maand.</p><p>Tel vervolgens de maandelijkse onderhoudstijd en kosten mee. Vrijgekomen tijd is pas nuttig als je weet welk werk ermee wordt gedaan. Het is niet automatisch een besparing op salaris of extra omzet. Bereken daarom geen terugverdientijd op basis van alleen de snelste demonstratie.</p></> },
    { id: "beoordelen", title: "Wanneer is de invoering geslaagd?", content: <><p>Beoordeel resultaat samen met kwaliteit en gebruik. Een sneller concept dat veel fouten veroorzaakt is geen verbetering. Een correcte workflow die alleen de bouwer kan bedienen, is nog niet goed overgedragen.</p><p>Leg vooraf een praktisch acceptatiecriterium vast, bijvoorbeeld: de medewerker kan de taak zelfstandig uitvoeren, de proceseigenaar kan uitzonderingen afhandelen en de uitkomst voldoet aan de afgesproken controlepunten. Leg ook de uitkomst van de test vast als die tegenvalt.</p><p>Bij het <Link href="/ai-groeipartner">groeipartnerschap</Link> bespreken we gebruik en knelpunten periodiek. Daarmee blijft de vraag of een toepassing helpt onderdeel van het werk.</p></> },
  ]} />;
}
