import Link from "next/link";
import KnowledgeArticle from "@/components/workspoor/KnowledgeArticle";
import { KNOWLEDGE_ARTICLES } from "@/lib/knowledge";
import { createPageMetadata } from "@/lib/seo";
const article = KNOWLEDGE_ARTICLES[2];
export const metadata = createPageMetadata({ title: article.title, description: article.description, path: `/kennis/${article.slug}` });

export default function AgreementsGuide() {
  return <KnowledgeArticle slug={article.slug} intro="Bruikbare AI-werkafspraken beschrijven waarvoor medewerkers AI mogen gebruiken, met welke informatie, wie de uitkomst controleert en waar zij terechtkunnen bij twijfel. Maak de afspraken herkenbaar voor een concrete taak en wijs een eigenaar aan." sections={[
    { id: "onderdelen", title: "Zeven onderdelen van werkbare afspraken", content: <><ol><li><strong>Taak en doel.</strong> Beschrijf welk werk de toepassing ondersteunt en waarvoor zij niet bedoeld is.</li><li><strong>Hulpmiddel en account.</strong> Leg vast welke toepassing en welk zakelijk account zijn goedgekeurd. Een privéaccount is niet vanzelf een toegestaan alternatief.</li><li><strong>Gegevens.</strong> Benoem welke bronnen en gegevens zijn toegestaan. Laat de verantwoordelijke vooraf privacy, vertrouwelijkheid en instellingen beoordelen.</li><li><strong>Controle.</strong> Schrijf op wat de medewerker altijd controleert, zoals feiten, bron, berekening, naam en toezegging.</li><li><strong>Besluit en verzending.</strong> Maak duidelijk wie het definitieve resultaat goedkeurt en gebruikt.</li><li><strong>Twijfel en incidenten.</strong> Bepaal bij wie een medewerker stopt, meldt of hulp vraagt.</li><li><strong>Onderhoud.</strong> Noteer eigenaar, datum en het moment waarop de afspraken opnieuw worden bekeken.</li></ol></> },
    { id: "voorbeeld", title: "Voorbeeld: een klantmail voorbereiden", content: <><p>Onderstaand voorbeeld is een startpunt voor bespreking, geen vastgesteld beleid voor jouw organisatie.</p><dl><dt>Doel</dt><dd>Een conceptantwoord maken op een algemene productvraag.</dd><dt>Toegestane invoer</dt><dd>Alleen goedgekeurde productinformatie en een geanonimiseerde beschrijving van de vraag. Geen klantdossier invoeren.</dd><dt>Hulpmiddel</dt><dd>De door de organisatie aangewezen toepassing en het goedgekeurde account.</dd><dt>Controle</dt><dd>De medewerker vergelijkt productgegevens, prijzen en toezeggingen met de oorspronkelijke bron. Ontbrekende informatie wordt nagevraagd.</dd><dt>Verzending</dt><dd>De medewerker past het concept aan en verstuurt het pas na controle.</dd><dt>Bij twijfel</dt><dd>Geen toezegging doen. Vraag de proceseigenaar om beoordeling.</dd><dt>Opvolging</dt><dd>De teamleider verzamelt knelpunten en bespreekt na dertig dagen of de afspraak werkbaar is.</dd></dl></> },
    { id: "invoeren", title: "Hoe laat je de afspraken landen?", content: <><p>Laat medewerkers de afspraak op een paar herkenbare situaties toepassen. Voeg ook een foutieve uitkomst toe: herkennen zij het probleem en weten zij wat ze daarna moeten doen? Pas onduidelijke formuleringen aan voordat je het document vaststelt.</p><p>Zet de actuele versie op een vindbare plek. Neem de uitleg mee bij de start van nieuwe medewerkers en bij veranderingen in hulpmiddelen of werkzaamheden. Een document zonder eigenaar of gebruiksgesprek veroudert snel.</p><p>In de <Link href="/ai-geletterdheid">teamtraining AI-geletterdheid</Link> oefenen we met twee werksituaties en maken we een concept voor teamafspraken. De organisatie stelt de afspraken vast; na ongeveer dertig dagen bespreken we het gebruik.</p></> },
    { id: "grens", title: "Is dit ook een volledig AI-beleid?", content: <><p>Nee. Deze gids helpt bij dagelijkse afspraken. Een organisatie kan daarnaast keuzes moeten vastleggen over inkoop, toegang, beveiliging, privacy, toezicht en bijzondere toepassingen. Laat die onderwerpen beoordelen door de verantwoordelijke inhoudelijke deskundigen.</p><p>Een ingevuld document of deelname aan een training is geen algemene nalevingsgarantie. Lees onze <Link href="/kennis/ai-geletterdheid-verplicht">uitleg over AI-geletterdheid en de verplichting</Link> voor de actuele bronnen en grenzen.</p></> },
  ]} />;
}
